apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-a-app
  labels:
    app: deploy-a-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-a-app
  template:
    metadata:
      labels:
        app: deploy-a-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: deploy-a-app
          image: ghcr.io/harryqin99/deploy-a-service:180f28de0fce58290ab04b99063cd67af0a7a146
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
