apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-a-app
  labels:
    app: deploy-a-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-a-app
  template:
    metadata:
      labels:
        app: deploy-a-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: deploy-a-app
          image: ghcr.io/harryqin99/deploy-a-service:2bd5740c16d0599b5796f8cf7ab7012c5ea39896
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
